canonical/knative-rocks

net-istio-webhook/rockcraft.yaml
net-istio-webhook/tests/test_rock.py
net-istio-webhook/tox.ini

Closes: https://github.com/canonical/knative-operators/issues/237
This Rock is based on upstream ko image: https://console.cloud.google.com/gcr/images/knative-releases/GLOBAL/knative.dev/net-istio/cmd/webhook 
To compare the rock I was using the latest upstream docker tag `v1.12.3` (that is also the version we are using in knative in kubeflow 1.9 [bundle](https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.9/stable/bundle.yaml#L176)).
**Steps for local comparison test**
```
rockcraft clean && rockcraft pack --verbosity=trace
sudo rockcraft.skopeo --insecure-policy copy oci-archive:net-istio-webhook_v1.12.3_amd64.rock docker-daemon:net-istio-webhook:v1.12.3
docker run gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v1.12.3
2024/11/12 08:27:01 Error building …
```

Add rock for `net-istio-webhook`

---

net-istio-controller/rockcraft.yaml
net-istio-controller/tests/test_rock.py
net-istio-controller/tox.ini

Closes https://github.com/canonical/knative-operators/issues/238
This rock is based on the image found here: https://console.cloud.google.com/gcr/images/knative-releases/global/knative.dev/net-istio/cmd/controller
To check that everything is as expected:
```
cd net-istio-controller
tox -e pack
tox -e export-to-docker
tox -e sanity
docker run gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v1.12.3
2024/11/12 11:27:01 Error building kubeconfig: failed to create client config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
docker run net-istio-webhook:v1.12.3
docker ps
docker exec -ti <container_id> bash
/ko-data/controller
2024/11/12 11:29:29 Error building kubeconfig: failed to create client config: invalid …
```

Add rock for net-istio-controller

---

knative-webhook/rockcraft.yaml
knative-webhook/tests/test_rock.py
knative-webhook/tox.ini

Closes https://github.com/canonical/bundle-kubeflow/issues/1138
Rock is based on the upstream ko image by `knative`: https://github.com/knative/operator/tree/knative-v1.12.4/cmd/webhook
To compare the rock I used the upstream docker tag `knative-v1.12.4`, that is the version we are using in knative in kubeflow 1.9 [charm](https://github.com/canonical/knative-operators/blob/track/1.12/charms/knative-operator/metadata.yaml#L31).
* Run the upstream image with `docker run`:
```
docker run gcr.io/knative-releases/knative.dev/operator/cmd/webhook:v1.12.4
panic: The environment variable "WEBHOOK_NAME" is not set.
This should be unique for the webhooks in a namespace
If this is a process running on Kubernetes, then initialize this variable via:
env:
- name: WEBHOOK_NAME
value: webhook
goroutine 1 …
```

feat: add `knative-webhook` rock

---

net-istio-webhook/rockcraft.yaml

Removes the user ubuntu from the rock's service. This workaround was not needed as we use the run user __daemon__.
With thte ubuntu user the service has issues while deployed.

Remove ubuntu user from service in `net-istio-webhook`

---

migrate/rockcraft.yaml
migrate/tests/test_rock.py
migrate/tox.ini

Closes: https://github.com/canonical/knative-operators/issues/239
This Rock is based on upstream ko image: https://github.com/knative/pkg/blob/release-1.12/apiextensions/storageversion/cmd/migrate/main.go
To compare the rock I was using the latest upstream docker tag `gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:232d6ffd88dfc0d0ec02c6f3a95520283d076c16b77543cee04f4ef276e0b7ae` (for some reason they dont have the tags in the kubernetes jobs, they rather use sha, although I have checked and they use the code from realease-1.12 branch and the name of the job is storage-version-migration-serving-serving-1.12.4 so I used the tag 1.12.4)
**Steps for local comparison test**
```
rockcraft clean && rockcraft pack --verbosity=trace
sudo rockcraft.skopeo …
```

Implement migrate rock

---

net-istio-controller/rockcraft.yaml

This PR Removes the user `ubuntu` from the `rockcraft.yaml` file. This workaround was not needed as we use the user `__daemon__`.
With the `ubuntu` user specified, we run into issues with the integration.

Remove ubuntu user from `net-istio-controller/controller` rock

---

knative-operator/rockcraft.yaml

Bump the `knative-operator` rock from `1.12.4` to `1.16.0` in preparation for CKF 1.10

chore: bump operator rock 1.12.4 > 1.16.0

---

knative-webhook/rockcraft.yaml

Bump the `knative-webhook` rock from `1.12.4` to `1.16.0` in preparation for CKF 1.10

chore: bump webhook rock 1.12.4 > 1.16.0

---

knative-operator/rockcraft.yaml
knative-operator/tests/test_rock.py

Closes https://github.com/canonical/knative-operators/issues/291
To unblock our integration of our rocks, until pebble will can handle read-only filesystems. 
1. Update all code and files to have `readOnlyRootFilesystem: false`
2. Add unit test to ensure the manifests in the final rock comply with the above assumption

Patch upstream code to set readOnlyRootFilesystem to false

---

migrate/rockcraft.yaml

* Upgrade migrate rock to 1.16.
* Add a comment for the go version source to facilitate next upgrades.
Close https://warthogs.atlassian.net/browse/KF-6930
In order to do the upgrade I went through the [spec](https://docs.google.com/document/d/1l_CrR_5U6NmDXpcoH2hkhVuoDzdpwFto6EwsylQ5vRw/edit?tab=t.0) in order to figure out what points I should check and:
* checked packages in base image `cgr.dev/chainguard/static` but didn't spot anything new
* Checked go version
* Checked code for changes
Also regarding the patch version, I used 1.16.0 since the last change in the branch was around October, when 1.16.0 was released.
Built and ran the image and noticed the same logs as the previous version of the rock (and the upstream image)
```
2025-02-13T16:13:21.954Z [migrate] …
```

chore: upgrade migrate to 1.16

---

net-istio-controller/rockcraft.yaml
net-istio-controller/tests/test_rock.py

* Upgrade source-tags
* Upgrade go versions
* Update packages according to new base image
* Remove copying files that are removed from upstream code
* Add comments to:
- outline which specific upstream image this rock corresponds to
- outline how to figure out which upstream image this rock should be updated to each time
- outline where base image is define in upstream
- outline where base image packages are defined in upstream
Fix https://warthogs.atlassian.net/browse/KF-6931
After looking at [ko images spec](https://docs.google.com/document/d/1l_CrR_5U6NmDXpcoH2hkhVuoDzdpwFto6EwsylQ5vRw/edit?tab=t.0), this is a summary of the changes and the process I followed:
* Changed base image from [distroless/static:nonroot](https://github.com/knative-extensions/net-istio/blob/release-1.12/.ko.yaml …

chore: upgrade net-istio-controller to 1.16

---

net-istio-webhook/rockcraft.yaml

* Upgrade source-tags
* Upgrade go version
* Update packages according to new base image
* Add missing environment values
* Add missing overlay and stage-packages according to base image
* Add comments to mention:
- which hash of the upstream image this rock corresponds to
- how to figure out the hash of the upstream image this rock should be updated to each time
- where the base image is defined in upstream
- where the base image packages are defined in upstream
Fix https://warthogs.atlassian.net/browse/KF-6932
Please see #26 for more details. Some references:
* https://github.com/knative-extensions/net-istio/blob/release-1.16/.ko.yaml
* https://github.com/knative-extensions/net-istio/blob/release-1.16/go.mod#L3
```
$ docker run --rm …
```

chore: upgrade net-istio-webhook to 1.16

---

knative-serving-controller/rockcraft.yaml
knative-serving-controller/tests/test_rock.py
knative-serving-controller/tox.ini

Added rock for Knative Serving Controller. See [source](https://github.com/knative/serving/tree/knative-v1.16.0/cmd/controller)
- Add rockcraft.yaml
- Add tests
- Add tox.ini
I uploaded rock to local microk8s. Then I activated it through `default-custom-images.json` in knative-serving charm from [here](https://github.com/canonical/knative-operators) and then run  integration tests. 
Status of `juju status --relations` after testing
```
Model     Controller                Cloud/Region        Version  SLA          Timestamp
kubeflow  github-pr-a184f-microk8s  microk8s/localhost  3.6.3    unsupported  17:05:19+02:00
App                   Version  Status  Scale  Charm             Channel       Rev  Address         Exposed  Message
istio-ingressgateway           active      1  istio-gateway …
```

Add `Knative Serving Controller` rock and tests

---

knative-serving-activator/rockcraft.yaml
knative-serving-activator/tests/test_rock.py
knative-serving-activator/tox.ini

Added rock for Knative Serving Activator. See [source](https://github.com/knative/serving/tree/knative-v1.16.0/cmd/activator)
- Add rockcraft.yaml
- Add tests
- Add tox.ini
I uploaded rock to local microk8s. Then I activated it through `config.yaml` in knative-serving charm from [here](https://github.com/canonical/knative-operators) and then run  integration tests. 
Status of `juju status` after testing
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.3    unsupported  14:39:26+02:00
App                   Version  Status  Scale  Charm             Channel       Rev  Address         Exposed  Message
istio-ingressgateway           active      1  istio-gateway     latest/edge  1378  10.152.183.83   no …
```

Add `Knative Serving Activator` rock and tests

---

knative-serving-controller/rockcraft.yaml

Closes #44, for details see the issue.
1. Deploy knative and istio charms from `latest/edge` and add relations as done in the [tests](https://github.com/canonical/knative-operators/blob/main/tests/test_bundle.py#L64)
2. Pack the rock and import to microk8s registry
3. Set the config in `knative-serving` charm to change the image to the local rock:
```
juju config knative-serving queue_sidecar_image=docker.io/library/knative-serving-queue:1.16.0
```
4. Create a Knative Service using the [yaml](https://github.com/canonical/knative-operators/blob/main/examples/cloudevents-player.yaml) from the test examples
5. Get the yaml of the knative service pod and grep for `readOnlyRootFilesystem`. should be set to `false`:
```
kubectl get po -n knative-test …
```

fix: patch upstream code to set `ReadOnlyRootFilesystem` of `queue-proxy` to `false`

---

knative-serving-autoscaler/rockcraft.yaml
knative-serving-autoscaler/tests/test_rock.py
knative-serving-autoscaler/tox.ini

Added rock for Knative Serving Autoscaler. See [source](https://github.com/knative/serving/tree/knative-v1.16.0/cmd/autoscaler)
- Add rockcraft.yaml
- Add tests
- Add tox.ini
I uploaded rock to local microk8s. Then I activated it through `config.yaml` in knative-serving charm from [here](https://github.com/canonical/knative-operators) and then run  integration tests. 
Status of `juju status` after testing
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.3    unsupported  14:39:26+02:00
App                   Version  Status  Scale  Charm             Channel       Rev  Address         Exposed  Message
istio-ingressgateway           active      1  istio-gateway     latest/edge  1378  10.152.183.83   no …
```

Add `Knative Serving Autoscaler` rock and tests

---

knative-serving-webhook/rockcraft.yaml
knative-serving-webhook/tests/test_rock.py
knative-serving-webhook/tox.ini

Added rock for Knative Serving Webhook. See [source](https://github.com/knative/serving/tree/knative-v1.16.0/cmd/webhook)
- Add rockcraft.yaml
- Add tests
- Add tox.ini
I uploaded rock to local microk8s. Then I activated it through `config.yaml` in knative-serving charm from [here](https://github.com/canonical/knative-operators) and then run  integration tests. 
Status of `juju status` after testing
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.3    unsupported  14:39:26+02:00
App                   Version  Status  Scale  Charm             Channel       Rev  Address         Exposed  Message
istio-ingressgateway           active      1  istio-gateway     latest/edge  1378  10.152.183.83   no …
```

Add `Knative Serving Webhook` rock and tests 

---

.github/workflows/on_workflow_dispatch.yaml
knative-operator/rock-ci-metadata.yaml

Closes: https://github.com/canonical/knative-rocks/issues/60
This pr: 
- add `workflow_dispatch` job for manual rock integration.

feat: `knative-operator` create rocks-automation-ci.yaml

---

knative-eventing-channel-dispatcher/rock-ci-metadata.yaml

Closes: https://github.com/canonical/knative-rocks/issues/54
This pr: 
Issue related to service file https://github.com/canonical/kfp-operators/issues/755

feat: `knative-eventing-channel-dispatcher` create rocks-automation-ci.yaml

---

knative-serving-activator/rock-ci-metadata.yaml
knative-serving-autoscaler/rock-ci-metadata.yaml

Closes: https://github.com/canonical/knative-rocks/issues/62
This pr: 

feat: `knative-serving-autoscaler` create rocks-automation-ci.yaml

---

knative-serving-activator/rock-ci-metadata.yaml

Closes: https://github.com/canonical/knative-rocks/issues/61
This pr: 

feat: `knative-serving-activator` create rocks-automation-ci.yaml

---

knative-eventing-mtping/rock-ci-metadata.yaml

Closes: https://github.com/canonical/knative-rocks/issues/58
This pr: 

feat: `knative-eventing-mtping` create rocks-automation-ci.yaml

---

knative-eventing-job-sink/rock-ci-metadata.yaml

feat: `knative-eventing-job-sink` create rock-ci-metadata.yaml
